### PR TITLE
Add .gitignore and remove all .DS_Store files.

### LINKED ISSUE #1: Remove .DS_Store
Currenty, there's a few unneeded `.DS_Store` files in your repo. I'd recommend you reach out to @Daniel-Pivonka for a proper .gitignore setup.

### PR DESCRIPTION
**Pull request by timflannagan**
Resolves #1

### CODE REVIEW

**Comment by Josh-Everett** [comment]
+1 LGTM

**Comment by Daniel-Pivonka** [comment]
id check out #3. this contains unnecessary files

**Comment by timflannagan** [comment]
@mlanotte1998 can you give me write access to the repo?

**Comment by nathan-weinberg** [comment]
LGTM

**Pull request merged**
