### PR TITLE
remove .DS_Store files

### PR DESCRIPTION
**Pull request by Daniel-Pivonka**
addresses #1. 
In my opinion this is better than #2. 
the .git ignore is unnecessary just dont commit .DS_store files.

### CODE REVIEW

**Comment by Josh-Everett** [comment]
I have to disagree - newly generated `.DS_store` files might repopulate and accidentally get committed. I think best practice would be to add them to the gitignore as @timflannagan1 suggests.
Please refer to [this github page](https://help.github.com/en/articles/ignoring-files)

**Comment by timflannagan** [comment]
@nathan-weinberg what do you think? I think Dan's just hunting for contributions.

**Comment by Daniel-Pivonka** [comment]
I don't see how they could be accidentally committed. You have to manually add files to a commit. Unless your doing 'git add .', which would be problematic, they will not be committed.

**Comment by timflannagan** [comment]
I'd recommend taking a look at an example of a [Swift .gitignore](https://github.com/github/gitignore/blob/master/Swift.gitignore)

**Comment by nathan-weinberg** [comment]
Respectfully, I must agree with @timflannagan1 and @Josh-Everett. Using a gitignore to prevent the addition of `.DS_Store` files is undoubtedly best practice. Recommend closing #3 and merging #2.

**Comment by timflannagan** [comment]
Closing as #2 has been merged.

**Pull request closed without merging**
